### ISSUE TITLE
Release for New Version

### ISSUE THREAD

**Issue by JonC613** [Pugmatt/BedrockConnect#118]
first of all,  this is amazing guys,  i downloaded the updated on my switch 2 hours ago and you already have a fix for it.  Amazing.

I haven't seen the compile release for it yet though,  it still the *.100 version.

**Comment by Pugmatt** [comment]
It's coming. Thanks for your patience.

**Comment by JonC613** [comment]
> It's coming. Thanks for your patience.

Thanks!  sorry for being naggy!  again thanks for everything you do.  is there a place we can 'buy you a beer' or something?  thought I saw a link for that once.  Also,  ever thought of porting this over the C#?

**Comment by Pugmatt** [comment]
No problem at all, glad to hear the software has been helpful! I do have a donation link at the bottom of the README, I appreciate it, don't feel compelled to though. :)

I haven't thought of porting it to C#, not sure if I see the need to. But if someone wants to take a whack at it, feel free. Might be kind of tough since resources like the Minecraft Bedrock Protocol library I use are also in Java.

**Comment by JonC613** [comment]
> No problem at all, glad to hear the software has been helpful! I do have a donation link at the bottom of the README, I appreciate it, don't feel compelled to though. :)
> 
> I haven't thought of porting it to C#, not sure if I see the need to. But if someone wants to take a whack at it, feel free. Might be kind of tough since resources like the Minecraft Bedrock Protocol library I use are also in Java.

lol,  zero need,  probably better for me to just how to do Java better (or at all :) ) what IDE do you use?  ever used visual studio code for coding in Java?

enough bugging you!  thanks again Matt!

**Comment by Pugmatt** [comment]
Release now out, thanks again for your patience: https://github.com/Pugmatt/BedrockConnect/releases/tag/1.5.6

I use IntelliJ for Java, but I do use Visual Studio Code sometimes for web dev stuff.
