### ISSUE TITLE
Script singelplayer

### ISSUE THREAD

**Issue by alberto28099** [Pugmatt/BedrockConnect#130]
Sorry I could do the same script but to run when entering with singelplayer or unblock the multiplayer tab I want it to connect to this server

https://www.spigotmc.org/resources/%E3%80%90dragonproxy%E3%80%91-%E2%80%94%E2%80%94-join-any-pc-server-using-mcpe-mcwin10.49610/updates
i have nintendo switch lite

**Comment by Pugmatt** [comment]
I'm honestly not sure what you're trying to do, could you expand on your current goal? You linked DragonProxy, which is currently not in development. I recommend using Geyser, which serves the same purpose and is currently active in development: https://github.com/GeyserMC/Geyser

**Comment by DespicableKee** [comment]
> Sorry I could do the same script but to run when entering with singelplayer or unblock the multiplayer tab I want it to connect to this server
> 
> https://www.spigotmc.org/resources/%E3%80%90dragonproxy%E3%80%91-%E2%80%94%E2%80%94-join-any-pc-server-using-mcpe-mcwin10.49610/updates
> i have nintendo switch lite

What I was able to get from this, is that you want to join this server through the same means that you are able to join the bedrockconnect server, correct? You have two options in this situation:

1. Add the server to BedrockConnect
2. Host your own dns server and instead of redirecting to BedrockConnect, redirect to the server you wish to connect to.

But either way, I would try to be more clear when submitting an issue, though this seems a bit off topic, as Pugmatt is not directly involved with this in any way. He doesn't make the program used to host your own dns server, nor is he affiliated with the program linked.

@alberto28099
