### ISSUE TITLE
Xbox connecting to Bedrock Connect

### ISSUE THREAD

**Issue by milton-mccann** [Pugmatt/BedrockConnect#138]
I have been using this for several months and have on the odd occasion struggled to connect as the “connect to open server” does not appear in the list. I reboot and normally this resolves the issue. 

However over the last 24 hours this does not seem to be working - I don’t have a PC to create my Owen bedrock connect.

thanks

**Comment by Pugmatt** [comment]
If you haven't already, you can try changing the secondary DNS to "1.1.1.1" instead of 8.8.8.8 or another public dns.

If you have a phone, you can also host it locally:

For Android, you can try this (Technically a PS4 tutorial, but should work the same): https://www.youtube.com/watch?v=ND_VFaAXC8M

For iPhone: https://www.youtube.com/watch?v=y2X_hhrsSAk

**Comment by milton-mccann** [comment]
Thank you - The iOS link worked first time!
