### ISSUE TITLE
Wont connect on xbox

### ISSUE THREAD

**Issue by XenonNitrate** [Pugmatt/BedrockConnect#163]
After trying so many solutions i am asking for help. It will put me in normal games and not bring up the bedrock connect server list. how can i fix this. tried multiple dns, i am on ipv4.

**Comment by Pugmatt** [comment]
If you've tried everything on the troubleshooting page, you can try hosting a local instance, and join through the LAN games menu rather than the DNS method. 

With both the local instance running and console on the same network, you can join it through the "Friends" tab in-game and see if it shows up under LAN servers. I have links for tutorials on different devices on the Troubleshooting page. https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting#im-having-lag-issues-or-getting-disconnected-when-on-or-trying-to-connect-to-the-bedrockconnect-serverlist
