### ISSUE TITLE
Safety Concern

### ISSUE THREAD

**Issue by Anon251** [Pugmatt/BedrockConnect#199]
I know I really shouldn't be putting this here, but I don't know anywhere else to ask this question, and no one on the internet seems to have discussed this. Maybe I'm just stupid and missed something. I am terribly sorry.

Do I risk getting banned by the console company or Microsoft by using this on my console? Is BedrockConnect against the terms of service of Xbox/PS/Switch/Minecraft?

Again, sorry.

**Comment by Pugmatt** [comment]
It's not discussed much because there really isn't a concrete answer. This is an unofficial tool used to bypass an unsupported feature on Microsoft/Mojang's end. As far as I know Mojang doesn't have anything stated in their TOS specifically about joining 3rd party servers on consoles, but this could be a different story on other consoles' ends.

Either way, use this tool at your own risk. This service has been up for almost 2 years at this point, hundreds of thousands of players using the service, and I haven't heard any scenarios about anyone getting banned or systems getting bricked. That being said, nothing is guaranteed about what companies are going to do in the future, and we don't have this knowledge. So use at your own risk and own discretion.
