### ISSUE TITLE
Trying to host a dns for my friends

### ISSUE THREAD

**Issue by TSSReal** [Pugmatt/BedrockConnect#204]
So the dns doesn't work for my buddies. They get directed to the normal servers instead of a serverlist. I'm using my public ipv4 in the .bat file and I've portforwarded 19132, 19133, 53. Still not working. On my phone when I launch mc and watch under the friends tab I can find a bedrock connect server that I can connect to but I cannot get it to work remotely. This is what the .bat file looks like after I enter the IP. I noticed that in your youtube video it said localhost:19132 instead of 0.0.0.0 and I have no clue to what difference that makes but maybe that is the problem. 

-= BedrockConnect =-
Local IPv4 IPs:
Realtek PCIe GbE Family Controller: 192.168.1.120

Which IP should be used for the DNS records: (public ipv4)

Server Limit: 100
Port: 19132

Loaded 0 custom servers
Bedrock Connection Started: 0.0.0.0:19132

**Comment by Pugmatt** [comment]
If you haven't already, take a look at the "Joining the Featured Servers still directs to the actual servers and not the serverlist..." on the troubleshooting page: https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting#joining-the-featured-servers-still-directs-to-the-actual-servers-and-not-the-serverlist

If your friends' networks are on IPv6, that could be the issue. Look at the solutions in that section of the troubleshooting page if this is the case.

If they don't have IPv6 enabled, then something is not allowing the connection to the DNS server on your network, or their network. Possible reasons:
- DNS server might not be port forwarded correctly
- Friends' routers might be forcing a DNS server on their whole network. If possible on their router, they can also set the DNS directly in their router settings.
- The game console might also just not be playing nice, and having trouble clearing the DNS cache. Which not much can be done past retrying or trying later.

> I noticed that in your youtube video it said localhost:19132 instead of 0.0.0.0 

That was just a visual change from an update since that video, so wouldn't be related.

**Comment by TSSReal** [comment]
@Pugmatt I guess that i have portforwarded the DNS server wrong then since the other DNS instances work for them but not mine. I wonder what mistake i have done in the portforwarding then since I've successfully portforwarded other things.

**Comment by definedrisk** [comment]
Possible suggestion: I spent several hours before I realised my ISP had a "helpful" firewall on their server end (in addition to the firewall / NAT built into the home router). So to be clear; I had login to my ISP via the web browser and use their web interface to make changes to this additional firewall (it was blocking port 53). I have been makinga lot is use of 'nslookup www.github.com 8.8.8.8` (replace 8.8.8.8 with your DNS server public IP).

**Comment by Inkybro** [comment]
@TSSReal Are you trying to host this on your own home server, or on a cloud platform like AWS?

If it's the latter... I think you need to open port 53 both TCP & UDP. I'm struggling to get this thing working, myself (on AWS), and this is the kind of stuff I do for a living.

I'm not saying you are doing so, but don't blame it on the kind author. It's probably just some little misconfiguration and/or an issue with your console(s) and/or Minecraft itself. I know I haven't gotten it working on switch (which I think I did read isn't even possible right now). I also can't get it to work on Xbox.

**Comment by definedrisk** [comment]
Some "key words" in case it helps: I've installed a permanent DNS server on my home network which I can access from static IP (port forward through router).  I had to add a master zone for each of the **8** [zones](https://github.com/Pugmatt/BedrockConnect#using-your-own-dns-server) now output by Bedrock Connect with `gweneratedns=true` argument e.g. mco.mineplex.com, play.inpvp.net etc.. Each of these 8 DNS zones has: 1) NS record to ns.ZONENAME e.g. ns.mineplex.com, ns.play.inpvp.net etc. , 2) A record static IP of your router (which is port forward to this DNS server) , 3) A record of ns.ZONENAME to this same static IP. This works for xbox, amazon kindle fire and PC (I hope to check nintendo switch in next 48hr and edit this comment accordingly). I think key issues are often firewall (switch it off while testing, is there another firewall / port blocking system in operation). My install of this Bedrock connect software is running on Windows 10 Home (fully updated) with nothing else installed. I'm using my own DNS software hosted on a NAS but I also got it working fine with mod0Umleitung running on same PC to begin with.  All the game devices need the static IP of the DNS server placing in their IP settings. NOTE: Also necessary to increment ports by +1 for the actual server as bedrock connect obv. uses the default 19132. So your local [bedrock server](https://www.minecraft.net/en-us/download/server/bedrock) should use 19133 which is [specified](https://github.com/Pugmatt/BedrockConnect#defining-your-own-custom-servers) in e.g. "myserver.json" and applied using the `custom_servers` argument. I port forward the 19132 and 19133 to same physcial IP but it does not have to be this way.
