### ISSUE TITLE
Nintendo Switch: Unable to connect to world.

### ISSUE THREAD

**Issue by matt-dolio** [Pugmatt/BedrockConnect#209]
I have a dedicated Ubuntu server (20.04 LTS, 8GB RAM, i5-2500T, 120GB SSD) that I am using to run a Bedrock server. I also run Java servers off of it quite often, as well as some other variety game servers.

I have set my DNS settings appropriately (104.238.130.180, 8.8.8.8), and can connect to the BedrockConnect server list. When I try to join on my public IP, I get an error regarding “Unable to Connect to World.”

I have done quite a bit of research to check my port forwarding rules, assuming user error before all else. This has been my first exploration into UDP for MC servers. I assumed the system would be actively listening on the IPv4 and v6 ports, but UDP does not actually do this, so I had to use an online nmap port scan to test UDP port forwarding. I have confirmed my port is correctly forwarded, and have accessed my server on PC Bedrock edition (using the public IP address, of course). 

Server is using latest Bedrock revision (1.17.2) as well as my NSW. Any help would be appreciated.

**Comment by matt-dolio** [comment]
I feel like I should add I have attempted the local connect as detailed in the “Before you open an issue” thread before opening this ticket.

**Comment by Pugmatt** [comment]
This issue has been common since 1.17, but is not BedrockConnect as we know. Once you begin joining a server from the BedrockConnect serverlist, it's completely off the BedrockConnect connection, so any errors being thrown at that point are from the server you're trying to join, or a bug in the game. It was definitely a widespread bug in the game itself for a while for all servers, which from what we know was related to recent Nintendo Switch firmware, but has since been fixed for most cases: https://github.com/Pugmatt/BedrockConnect/issues/196

I suspect the bug is still out there, as with cases like this. Since the bug is outside of BedrockConnect as we know so far, there unfortunately isn't much I can do or know what the solution would be. But, I would recommend doing the following though:
- Make sure your Nintendo Switch is updated to the latest system update
- Do you happened to be using the official Bedrock dedicated server software? (https://www.minecraft.net/en-us/download/server/bedrock) If so, my other suspicion is that the server software supplied by Mojang could be having issues with the console versions of Minecraft. (Although through my own personal testing, I've been able to connect to my own local Bedrock server on the Switch fine without issue, so could be an issue that's different system to system) If you aren't using already, I'd be curious to see if your console would be able to join a server hosted on different server software, such as CloudburstMC, a 3rd party server software: https://github.com/CloudburstMC/Server
- I noticed you said your server is on 1.17.2. If you are using the official Bedrock dedicated server software, the latest is technically running labeled version 1.17.2.01, but you might have been referring to that anyway

**Comment by Pugmatt** [comment]
Just realized by "NSW" you probably meant Nintendo Switch. If so, ignore that first bullet point.

**Comment by matt-dolio** [comment]
I know for certain my game is running v1.17.2, I’m unsure about the EXACT version of the server, I will check the revision when I’m at my computer next. I’ll have to give the Cloudburst server a shot as well. I’ll keep you updated with how it goes!

**Comment by matt-dolio** [comment]
To confirm, the Bedrock software I was running was 1.17.2.01. My Nintendo Switch is on the latest update (12.0.3), and Minecraft the latest as well (1.17.2). I tried using Cloudburst, but it appears it is not updated yet for 1.17. I will be doing more research based on the ticket you linked me and will see if any of those fixes works for me.

**Comment by Pugmatt** [comment]
Sorry, had mixed it up with this one which is made by the same group, which is on 1.17: https://github.com/CloudburstMC/Nukkit

**Comment by matt-dolio** [comment]
It looks like that specific update (12.0.3) for the Switch is the one that got yoinked shortly after release, with Nintendo citing network issues and other serious concerns. I am one of the unfortunate that managed to update before it got pulled. If I can't figure it out with one of the workarounds or the Nukkit link you just posted, I'm likely going to have to stick it out until Nintendo updates the system.

**Comment by matt-dolio** [comment]
My significant other has a Nintendo Switch Lite, I will see what version she is running and try connecting on her device. Since it certainly appears that BedrockConnect is not at fault here, I'm not going to drag out this ticket with miscellaneous troubleshooting regarding this issue. Thanks again for your help!

**Comment by matt-dolio** [comment]
Thought the dev would like to know, this has been resolved as of the Switch 12.1.0 update. My server works great, and this tool makes it happen!

**Comment by Pugmatt** [comment]
Good to hear, thanks for letting me know!
