### ISSUE TITLE
Question about public DNS

### ISSUE THREAD

**Issue by rog1n** [Pugmatt/BedrockConnect#21]
Hello, I checked if I used internet from 4G (smartphone) to my switch the public DNS of bedrockConnect work great but if I use internet from my ISP then I can not connect.

Is possible to say what the ISP is blocking to try talk with them to resolve?

**Comment by Pugmatt** [comment]
I'm honestly not too sure what the ISP would be blocking, it might not be them blocking but more that the DNS server is having trouble connecting because of your internet type.

If you have a PC, you can also try hosting the BedrockConnect software locally: https://www.youtube.com/watch?v=AW5X7-qnvLk
