### ISSUE TITLE
I get some bullshit error while trying to run the program

### ISSUE THREAD

**Issue by LuaLighter** [Pugmatt/BedrockConnect#237]
![image](https://user-images.githubusercontent.com/72767525/143689536-13f7ad7b-2c7d-45db-a3c4-7ed26c41d384.png)

**Comment by kmpoppe** [comment]
Are you possibly running a Bedrock Server instance on the same server? 

Then, because of https://bugs.mojang.com/browse/BDS-3989 the BDS is also listening on port 19132 even though you might have configured another IPv4 port.

As BedrockConnect can _only_ bind to 19132 (because that's the only one the game connects to) you will simply _not_ be able to have a BDS instance and Bedrock Connect listening on the same IP in your home network.

If you give your local machine a second IP to listen to, just put BDS and BC on different IPs and you'll be fine.

HTH. Kai

**Comment by kmpoppe** [comment]
@LuaLighter please close this issue if you could resolve it. Thanks!

**Comment by LuaLighter** [comment]
I fixed it by messing with the ports, thanks
