### ISSUE TITLE
Java exceptions generated

### ISSUE THREAD

**Issue by Zarh2002** [Pugmatt/BedrockConnect#24]
I get multiple java exceptions:

![image](https://user-images.githubusercontent.com/63420352/78926342-8bdb2500-7a62-11ea-90f9-8837e86b815d.png)

**Comment by Pugmatt** [comment]
That error means you have another program running that is using that port. Also, the port should probably stay as 19132, as the DNS bypass only works for the BedrockConnect server when it's port 19132. If you're doing that because you a game server that's on port 19132, you should change the port on that and leave the port on BedrockConnect as port 19132.

**Comment by Zarh2002** [comment]
Ok, so I installed this on my Minecraft server. It’s running two servers on 19134 and 19136. I should then run bedrockconnect on 19132?

**Comment by Pugmatt** [comment]
That is correct.

**Comment by Zarh2002** [comment]
Great - that issue is solved and bedrock connect started. Switch is not loading the server selection screen, though. I have upd port 19132 forwarded for outbound on the server, anything else I’m missing? Local NSlookup works; if I use NSlookup on another network computer, no response

**Comment by Zarh2002** [comment]
All working now - port 53 was not forwarded.
