### ISSUE TITLE
[Feature Request]: Seperate connecting and adding a UserServer and allow changing of already existing userservers 

### ISSUE THREAD

**Issue by CrafterPika** [Pugmatt/BedrockConnect#266]
First currently adding a userserver to BC's ServerList requires the User to enter the server info into "Connect to a Server" and ticking the option "Add to Serverlist", then join server. This can be quite annoying specifically for people who want to add all their servers for example from a Mobile device to BedrockConnect. 
Second, right now you cannot edit exiting server information you can only remove them, Example: `test.geysermc.org` changed to `test1.geysermc.org`, to change this in the ServerList, I'll have to remove the server and do first mention procedure.

Splitting "Connect to a Server" into "Direct Connect" (Basically Connect to a Server without UserServer adding) and "Add a Server" (Adding a UserServer without directly connecting) (or however you want to call it).
Add an option "Edit a Server" to edit existing UserServer.

mostly meant for convenience of use :P

- PIka

**Comment by Pugmatt** [comment]
I agree with the "Add To Serverlist" checkbox issue, I'll look into making that enabled by default since that's usually the case 90% of the time when connecting to a server.

For adding more options such as editing, my biggest gripe with not adding it before was keeping the UI as simple as possible and not too crazy with buttons. But I think it should be possible to still add this while keeping it clean. I'm thinking right now something like (In terms of order on the list):

- Connect to a Server
- Manage Server List
   (Once clicked/opened)
   - Edit a Server
   - Remove a Server
- Exit ServerList
- (Usual servers listed)

Could also put Direct Connect in the parent window, and then Add a Server to the Manage Server List menu, but I think it would be good to have the ability to add a server in one button click like it is now.

**Comment by CrafterPika** [comment]
This actually makes more sense, than what I was thinking of.
Just my point stays there should be added an Option to Manage Server List to only add an Server, because if someone wants to copy their server list from a mobile device for example to BedrockConnect having to:
1. Join a Server to add it to the list
2. Then leave the Server
3. Re-join BC's ServerList
4. Repeat above
Can be quite time consuming in such cases.

**Comment by Pugmatt** [comment]
Newest version (https://github.com/Pugmatt/BedrockConnect/releases/tag/1.17) now has a "Manage Server List" button containing a Add, Edit, and Remove button. Add server button can be used to add servers to the list without leaving the serverlist server.
