### ISSUE TITLE
Can't connect to BedrockConnect

### ISSUE THREAD

**Issue by TheOverlordBunny** [Pugmatt/BedrockConnect#287]
### What happened?

As the title says, it won't let my friend connect to BedrockConnect (I don't have an Xbox/PS4 so I can't test this).
Basically, he's on Xbox One, and he put in the DNS thing correctly, both the Primary and the Secondary one. But when he joins (any) server, it just takes him to the actual server. Any help? We're using the 104.238.130.180 one, by the way.

### Excepted Behaviour?

We expected it to go to the server list

### Steps to reproduce.

1. Put in DNS settings
2. Join Minecraft
3. Go to Servers
4. Join any server (Hive, CubeCraft, Lifeboat, etc.)
5. Goes to the actual server, not the server list. 

### Minecraft Bedrock Version

1.18.20

### Console

XBox

**Comment by Pugmatt** [comment]
Current known ways of how to fix this are listed on the troubleshooting page under "Joining the Featured Servers still directs to the actual servers and not the serverlist...": https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting#joining-the-featured-servers-still-directs-to-the-actual-servers-and-not-the-serverlist

Most of the time it's because of IPv6, which is listed on the last bullet point of that section.
