### ISSUE TITLE
Is it or will it be possible for legacy versions to join? (ps3, vita)

### ISSUE THREAD

**Issue by paj1s** [Pugmatt/BedrockConnect#297]
I think the last update for the legacy versions is update aquatic, so it wouldn't be that old. I know the problem may be in that the legacy version are complete different game but the also have multiplayer, so is there a possibility?

**Comment by tomrow** [comment]
Likely not, as the legacy console heavily relies on matchmaking and party systems of the console's network service (PSN, XBOX Live, Nintendo Network) to advertise multiplayer games and this version doesn't have dedicated/sponsored servers.

**Comment by Pugmatt** [comment]
As stated by tomrow above, this would not be possible due to the multiplayer in the Legacy versions working completely differently. The modern console versions, Bedrock Edition, works since it has the support in the game for 3rd-party servers, and BedrockConnect basically just uses a bypass to access that feature. The Legacy versions' multiplayer are all through matchmaking/party systems, I don't believe there is any server software available for Legacy edition for people to host servers with on their own hardware, or functionality on Legacy versions to join any such thing.

So, getting Legacy versions to work would require heavy game modding, converting protocol packets, creating server software, etc. Not realistically possible, unfortunately, and would require more than just something like BedrockConnect to work.

If anyone knows if I'm wrong on any of the above, feel free to correct me.
