### ISSUE TITLE
Patched for 1.19 on switch?

### ISSUE THREAD

**Issue by TopLightHub** [Pugmatt/BedrockConnect#305]
### What happened?

I tried using 104.238.130.180 and 173.82.100.84 and it didn't work. it worked before when I used it but now it doesn't. 
It doesn't join the server list it just joins the server I clicked on in the server list

### Excepted Behaviour?

expected it to open the server list

### Steps to reproduce.

Open Minecraft
Go To Servers
Join any server
Joins the server I clicked on instead of opening the server list

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/84365142/172546661-73f571c2-cd1a-47be-bb13-d1c9146a60f2.png)

### Minecraft Bedrock Version

1.19.1

### Console

Nintendo Switch

**Comment by EightBitRG** [comment]
I can confirm that this is also happening to me

**Comment by Pugmatt** [comment]
This has not been patched, it is still working for others. If you are being directed to the actual featured server instead of the serverlist, then the DNS either needs to be re-configured in your console's internet settings, or there was a change to your network/router. All known solutions for fixing this issue can be found on the troubleshooting page: https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting#joining-the-featured-servers-still-directs-to-the-actual-servers-and-not-the-serverlist

**Comment by ethpsa09** [comment]
can confirm  its working for me, i used 173.82.100.84 as my primary and 1.1.1.1(cloudflare dns) as my secondary

**Comment by braindigitalis** [comment]
I think something somewhere is being cached. I'm getting this behaviour with a self hosted instance, where I've put the zones into my bind instance used for the whole network.
are there more zones than listed in the bind how-to in the root of the repository?
Thanks!

**Comment by SniperJo2010** [comment]
still not working for me.

**Comment by SniperJo2010** [comment]
pls patch!

**Comment by EightBitRG** [comment]
> can confirm its working for me, i used 173.82.100.84 as my primary and 1.1.1.1(cloudflare dns) as my secondary

Thanks this fixed it for me

**Comment by SniperJo2010** [comment]
I tried all the troubleshooting options and used the same DNS as you hundreds of times but it never works. I’ve used both available primary in the US with google and cloud flare DNSs. Never works!

**Comment by SniperJo2010** [comment]
Always takes me to the actual server instead of any of the redirection servers. Pls patch!
