### ISSUE TITLE
Possible ipv6

### ISSUE THREAD

**Issue by Who-Cares69** [Pugmatt/BedrockConnect#318]
Would it be possible to ever In the future make this available to people who are on ipv6 and can't change to ipv4?

But this would mostly be a quality of life thing as there are other ways to go on servers on Xbox but this would be by far the best and most stable compared to the other methods and it would be amazing if it could possibly in the future be compatible with ipv6.

**Comment by Pugmatt** [comment]
This isn't possible not because it's not implemented by us, but because it's unfortunately not possible to set custom IPv6 DNSs on most game consoles, specifically Xbox. So unfortunately since its not possible due to console restriction, there is nothing we can do from our end.

If someone can't disable IPv6, they can also try setting the IPv6 address of the BedrockConnect DNS into their router directly, which would be the only other solution other than straight up disabling IPv6. (Which the troubleshooting contains the address and info and how that can be tried) 

All options that are currently known possible to get around the IPv6 restriction can be found in the troubleshooting. https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting#joining-the-featured-servers-still-directs-to-the-actual-servers-and-not-the-serverlist
