### ISSUE TITLE
PS4 Dns dont work

### ISSUE THREAD

**Issue by Loukoumpetit** [Pugmatt/BedrockConnect#323]
### What happened?

Hello, I tried the 5 DNS on my Ps4 but instead of showing me the interface to add the server, it joins the default server.

### Expected Behaviour?

Its after the update 1.19.21

### Console

1.19.21

**Comment by CrafterPika** [comment]
Known issue,
<a href="https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting#joining-the-featured-servers-still-directs-to-the-actual-servers-and-not-the-serverlist">Wiki:Troubleshooting</a> mentions it.

Since it’s an PS4, you can join BedrockConnect using LAN game.
1. Download the latest `BedrockConnect-1.0-SNAPSHOT.jar` from https://github.com/Pugmatt/BedrockConnect/releases/latest
2. Run it with Java: `java -jar BedrockConnect-1.0-SNAPSHOT.jar nodb=true` 
3. Open Friends Tab on Minecraft.
4. Look for BedrockConnect and join
- if you cannot find BedrockConnect in the friends tab as LAN game, ensure console and computer are on the same network.
