### ISSUE TITLE
Not connecting at all

### ISSUE THREAD

**Issue by JustZakary** [Pugmatt/BedrockConnect#36]
Sorry to leave another issue here but I'm kinda having trouble.

The dns up works perfectly on my and all my friends xboxs except one.
This person doesn't have the Minecraft server list changed at all if she joins one it takes her to that server and not the server list.

I'm wondering what could cause this problem? A setting that is changed from default? It's not her ISP because I have the some provider and it works fine for me.

Edit:
The IP is correct we put it in 5 times

**Comment by Pugmatt** [comment]
If everything has been tried, the only thing I could think of is the same issue as discussed here might be happening: https://github.com/Pugmatt/BedrockConnect/issues/25

I'm going to be making an alternative tutorial for Xbox and PS4 in the next couple of days that uses the LAN server section in Minecraft to connect to the serverlist, instead of the DNS since it's seems to be an issue with some Xbox's or routers.

The tutorial will essentially be this if you want to check it out and try it yourself:
- On PC, Mac, or Linux, download this JAR: https://github.com/Pugmatt/BedrockConnect/releases/download/1.4.2/BedrockConnect-1.0-SNAPSHOT.jar
- Make sure you have Java 8 or higher installed.
- In command prompt or terminal, run the following command:
```java -jar BedrockConnect-1.0-SNAPSHOT.jar nodb=true```

At this point the serverlist server should be running. Make sure this is also running on the same network as the Xbox. When in Minecraft, go to the "Friends" tab, and the server should be showing under LAN servers and available to join.
