### ISSUE TITLE
S̵o̵n̵y̵ ̵c̵u̵r̵r̵e̵n̵t̵l̵y̵ ̵a̵p̵p̵e̵a̵r̵s̵ ̵t̵o̵ ̵b̵e̵ ̵b̵a̵n̵n̵i̵n̵g̵ ̵a̵c̵c̵o̵u̵n̵t̵s̵ ̵t̵h̵a̵t̵ ̵u̵s̵e̵ ̵t̵h̵e̵ ̵m̵a̵i̵n̵ ̵B̵e̵d̵r̵o̵c̵k̵C̵o̵n̵n̵e̵c̵t̵ ̵i̵n̵s̵t̵a̵n̵c̵e̵

### ISSUE THREAD

**Issue by Neph-Oo** [Pugmatt/BedrockConnect#409]
### What happened?

I've convinced some friends to give a try to BedrockConnect, one of them can no longer connect to her account. 

### Expected Behaviour?

Don't be banned. :)

### Steps to reproduce.

- Change primary DNS to the main BedrockConnect instance and secondary DNS to google (8.8.8.8)
- Join a server and play
- Pray

### Screenshots/Videos

![ban](https://github.com/Pugmatt/BedrockConnect/assets/14979535/43b3dab0-500e-4628-bb92-389c5c9bf20c)

### Minecraft Bedrock Version

1.19.83

### Console

PS4

### Additional Context

We're not **sure** that the use of the main BedrockConnect instance is the reason for the ban, nor that's really an account suspension. 
But the probabilty is pretty high because we set up the primary DNS to the main BedrockConnect instance one day before the account suspension AND it happened while we were playing on my GeyserMC/Spigot server (port 25565 / UDP). 
This person was kicked of the game and Party Chat (Sony VoIP system) suddently and she can no longer use her account (Sony/PSN account). 
The only reason given on the console was: "Too many connections attempts", which is obviously useless information.

We asked Sony for the reason for the account suspension (using this [link](https://ps-support.playstation.com/s/psn-suspension-status?language=en_US&locale=en-us)) but they haven't replied so far. The next step will be to try to contact Sony customer support, I will update the issue if I can get more information from them. 
Any help/ideas will be appreciated.

**Comment by Pugmatt** [comment]
Very strange, I will see what I can find. This is the first time anything ban related has been reported to the project, so not entirely sure what could have occurred, but I did do some research on what these errors could mean. From what I can see in that screenshot (although I roughly translated it, so may not have read everything correctly), the error on the screen doesn't appear to be a hard ban/suspension, but it seems to indicate too many requests are being sent to the PSN servers or too many login attempts, so their account is possibly temporarily timed out from connecting. From what it looks like it recommends resetting the password. When I look up pictures of PS4 error messages that relate to full-on account suspension, the wording on those screens seems to usually be mentioning some kind of suspension due to breaking their TOS, but that's not what we're seeing here.

I don't believe BedrockConnect would be causing connection issues like this, but I'll see what I can find. Only thing I can think of currently, is the DNS may not be connecting correctly, but surely the system shouldn't be acting that way either way with a DNS set in the console settings. If it was a ban specifically targeting the use of the BedrockConnect DNS, we would probably have more reports of this, as this has been the only report received of this so far. (Not throwing out the idea BedrockConnect may be causing it, but more just my current line of thinking)

Do you know if your friend is still able to log in to their PSN account from outside the console, such as the Playstation website on a phone/computer? Or if they retrieve a password reset email when attempting to reset it? (https://www.playstation.com/en-us/support/account/password-reset-psn/#reset)

**Comment by Neph-Oo** [comment]
Thanks for your reply @Pugmatt. That why I oppened the issue in the first place: wanted to know if you or anyone else had ever had to deal with this sort of thing. The fact that you haven't received anything like that so far reassure me. 

And you're right, the error on the screenshot (in french) doesn't seem to be an account suspension, you translation is correct. That why I'm **not sure** if it's really a BedrockConnect problem. 
Sony didn't send any mail (which is what they are supposed to do when suspending an account, sending a mail with the reason of the ban, the duration of the suspension, etc). 
Even when requested explicitly, we receive nothing from them and it's the same for password reset: we reveice nothing from Sony. 

Also, an important clarification: I know for sure that the DNS trick doesn't work on her ps4. We had to rely on the BedrockConnect app (BedrockConnet on LAN) for her to connect to the Geyser server. So:
> Only thing I can think of currently, is the DNS may not be connecting correctly, but surely the system shouldn't be acting that way either way with a DNS set in the console settings.

Do you think that failling attempts to request A record from the primary DNS before trying the secondary might have blocked the account ?

**Comment by Neph-Oo** [comment]
Ok. So, it's look like from the Playstation site, you can't do anything either, but it's definitively not an account suspension. You was right.

The gmail address associated with the PSN account **can't receive any mail at all and that the real problem**. My friend has lost her password and therefore can't login from another web browser (only from the gmail app on her phone) to check what's going on with the gmail account.
 
Unfortunately, I can't even provide a network packet analysis to see what's really going on with DNS. And, with this problem with Gmail, many others things may have gone wrong. 

Thanks again for your help even though I'm a bit frustrated that I took your time without knowing for sure if this could be related to DNS denial of service (the ps4 rejecting DNS requests). 

I think **it should be considered unrelated to the use of BedrockConnect** so I'll change the title and close the issue.
