### ISSUE TITLE
COuld not connect 'Outdated server' when trying to access BC server list from xbox.

### ISSUE THREAD

**Issue by tofuwarrior** [Pugmatt/BedrockConnect#419]
### What happened?

XBOX client auto updated to 1.20.11  and now when I try to access the server list it gives 'Outdated Server' error.
Tried several of the public DNS options, all the same problem.

Guessing this is some incompatibility between BC and  bedrock 1.20.11?

### Expected Behaviour?

Expected to see the server list as usual.

### Steps to reproduce.

Update DNS on xbox to BC public server.
Update minecraft bedrock client to 1.20.11  on xbox 
Open minecraft bedrock on xbox.

### Minecraft Bedrock Version

1.20.11

### Console

XBOX One S

**Comment by drake-pamplin** [comment]
Looks like @Pugmatt or one of the other maintainers just needs to update the project to the latest version. Given how prompt they have been in the past, I cannot see this issue lasting long follow the below thread to see when it gets patched:

https://github.com/Pugmatt/BedrockConnect/issues/420

**Comment by tofuwarrior** [comment]
Is it just a case of editing that file to the latest bedrock version number?

**Comment by sircurse** [comment]
It would be nice if the version could be imported from a external file, I agree that the team usually update the version fast but sometimes it takes several hours, for me in my case, I was in the middle on editing and testing my mod pack, unfortunately I can play only on console, and now I'm stucked until the update... Right now it's being 6 hours long, and due to my time zone now I'm shutting down and the players of my server will also not be able to play until I wake up tomorrow and hope the update to the proxy was done... 

Just a suggestion if it could be possible...

**Comment by kmpoppe** [comment]
Good timezone everyone.

The update will be communicated in #420 and through a new [release](https://github.com/Pugmatt/BedrockConnect/releases) being published.

As this project relies on external projects also updating, we ask for your patience.

I will close this issue as it describes well known behaviour after an update to Minecraft Bedrock.

Kai
