### ISSUE TITLE
Help w/ troubleshooting

### ISSUE THREAD

**Issue by hasankayra04** [Pugmatt/BedrockConnect#483]
### What happened?

Let me try to give an example.
I can join directly test.geysermc.org and i can join everything works fine.
But when i try to connect through BedrockConnect i get "Please check your connection to internet and try again. Unable to connect to world."

How should i diagnose this? Checked dns logs, no microsoft services are blocked. I have firewall on, and only allow 19132 as udp. I don't think i need to allow any other port. Idk what else the issue could be.

### Expected Behaviour?

Work?

**Comment by Pugmatt** [comment]
Just for clarification, is this error occurring when joining the custom-hosted BedrockConnect instance? Or is this error occuring when connecting to a game server from BedrockConnect.

**Comment by hasankayra04** [comment]
I am self hosting the BedrockConnect instance. There isn't anything custom really, didn't change anything. Just (idle kick time, max servers that can be saved etc. was changed), and when i try to connect a server from BedrockConnect i get the message "Please check your connection to internet and try again. Unable to connect to world.". If try to join the same server without using BedrockConnect, i can join fine.

**Comment by Pugmatt** [comment]
Okay got it.  If you are receiving an error during the connection to a server from BedrockConnect, that would be an issue with the game server you are trying to join, not so much BedrockConnect. Most common reasons is either the server is not port forwarded correctly or is not currently online, or the server is a Java Editions server. (In which case you would also need to use a proxy like Geyser in order to connect, as Java Edition is not native to Bedrock Edition  https://www.youtube.com/watch?v=B_oPHl5gz_c)

> If try to join the same server without using BedrockConnect, i can join fine.

Is this by connecting to the server through Minecraft Bedrock Edition on Windows 10, or Minecraft Java Edition? Or some other means

**Comment by hasankayra04** [comment]
I am connecting with PE, to test.geysermc.org which is setup correctly. I'll try to attach a video later.

**Comment by hasankayra04** [comment]
Problem solved after logging out and back in. Maybe something with sessions? Idk. Sorry for taking your time.
