### ISSUE TITLE
connection timed out unable to connect to world

### ISSUE THREAD

**Issue by Nagol12344** [Pugmatt/BedrockConnect#54]
when I upgraded to 1.16 I couldn't join FIX IT

**Comment by CodeAX2** [comment]
Same issue here. Likely due to how the service works (ie connecting to a server that then reroutes you). I assume the server it connects you too is either down for maintenance (to update to 1.16.0) or is still on the old version. I'm sure Pugmatt is aware of the issue.

**Comment by mars0124** [comment]
I would also assume Pugmatt is aware, and will get to it as his life permits.  Until then we'll all need to wait patiently.

I look forward to the release, when it comes.  Thanks for all you do Pugmatt.

**Comment by CodeAX2** [comment]
After looking over the code quickly, it seems that this project relies on the NukkitX protocol in order to host the server. NukkitX itself is not updated yet, since it's most recent version (bedrock-v390 which is what is used in BedrockConnect) only supports 1.14.60, and not 1.16.0. So it will likely be a few days until NukkitX is updated, and therefore a few days until BedrockConnect is also updated.

**Comment by mars0124** [comment]
I was thinking about running a dummy bedrock server with a command block and websockets as a workaround... but I have no idea if that's possible or how to go about it yet.  Time for some research!

**Comment by Pugmatt** [comment]
Working on an update now. Thank you for your patience guys.

**Comment by CodeAX2** [comment]
It looks like there is a branch of NukkitX Protocol that supports 1.16.0 (v407), so perhaps use that? I cloned BedrockConnect to see if I could get it to work locally with v407

**Comment by Pugmatt** [comment]
Yeah, that's what I'm currently looking into.

**Comment by CodeAX2** [comment]
It looks like we have to wait for NukkitX Protocol to be released for 1.16 properly (unless you want to completely change how your dependencies are structured, which I doubt it a good idea). Since the NukkitX Maven Repo does not have v407 included yet. It seems they have been working on their new branch quite a bit today, so I assume it will only be a few days until NukkitX is updated, then it appears pretty straightforward to get BedrockConnect working (just gotta change the dependencies in pom.xml, rewrite Bedrock_v390.java to be Bedrock_v407.java (with tweaks to allow for 1.16.0) and it should all work (if I understand everything correctly). All of the errors are only coming from NukkitX, so its just a waiting game at this point.

**Comment by Nagol12344** [comment]
ok that makes sense, we al have to wait for NukkitX.

**Comment by Nagol12344** [comment]
it looks like this is already been put as a issue on their GitHub.

oh here's the link for the github [](https://github.com/NukkitX/Nukkit).

they said they're working on it,we just have to wait.

**Comment by Tristan7s** [comment]
> when I upgraded to 1.16 I couldn't join FIX IT

With all due respect slamming your feet on the ground and screaming at him to fix it is super rude and entitled. I see you've forked projects so why don't you give it an attempt? Instead of being so entitled towards PugMatt and the Nukkit team.

Thank you PugMatt for this awesome tool, I look forward to playing with my switch buddy whenever it's ready :)

**Comment by Nagol12344** [comment]
okay I was a little annoyed that I only got two uses for one day

**Comment by Tristan7s** [comment]
I know that most likely wasn't your intent and you are excited for the new 1.16 update, just remember this is a project that takes time, and probably money as he is hosting dns servers for us all. Only got 2 uses is the same as being able to play with friends or on custom servers twice. We're all very excited to play with all of our friends but at the end of the day Pugmatt isn't really forced to fix anything. Pugmatt dm me your paypal or post a donation link so I can help support the projects you put your time and effort into :)

**Comment by Nagol12344** [comment]
PayPal is at the bottom of the read me

**Comment by gmwrenchead** [comment]
Confirmed the issue both for me and a friend. We will be patient. Thanks for doing this Pugmatt!

**Comment by Nagol12344** [comment]
ok we know what is broken

**Comment by Pugmatt** [comment]
BedrockConnect is now updated to 1.16! Thank you for everyone's patience. Keep in mind there a good amount of servers out there that are not 1.16 yet, so it's not going to work for all servers until they update as well.
