### ISSUE TITLE
Bot is down

### ISSUE THREAD

**Issue by RestartB** [Pugmatt/BedrockConnect#551]
### What happened?

Looks like the BCMain bot is down, BCMain1 is down as well I believe. My friends are trying to connect using BCMain but can't, and looking at its Xbox profile, it's showing as offline.

### Expected Behaviour?

Able to connect to Minecraft servers using BCMain in the friends list

### Screenshots/Videos

<img width="317" alt="image" src="https://github.com/user-attachments/assets/ada2e108-a17f-4163-871c-e42febfc19ab">

### Console

All Consoles

**Comment by RestartB** [comment]
Update: looks like BCMain1 might be up

**Comment by Pugmatt** [comment]
I believe it's due to some outages occurring on Microsoft's end https://support.xbox.com/en-US/xbox-live-status

Currently trying to re-authenticate the bot, but having issues. May need to wait for the outages to be fixed on Microsoft's end. BCMain1 as you said appears to be up, so would recommend adding that bot for now.

**Comment by RestartB** [comment]
yeah, I've told them to switch to BCMain1 and that seems to be working for them. thank you for your hard work 🙏

**Comment by Pugmatt** [comment]
Was able to authenticate BCMain finally, that one should now be back up and working as well.
