### ISSUE TITLE
Nintendo switch 1.16.21 "Coming Soon" issue

### ISSUE THREAD

**Issue by Ianbv17** [Pugmatt/BedrockConnect#84]
When I try to use the BedrockConnect to enter a server, it shows a label on the Server listo that says "Coming Soon" So With the DNS changed I can't access nether the Mojang-aproved servers and my customized servers. 
![IMG-20200825-WA0099](https://user-images.githubusercontent.com/70251199/91255800-fd222880-e722-11ea-98d7-d6e22e755925.jpg)

**Comment by Wilainky** [comment]
Hello

**Comment by Wilainky** [comment]
Yeah me too

**Comment by STSparks07** [comment]
Tengo un problema con los servers online que puedo hacer?

**Comment by Yuga722** [comment]
I'm having the same problem :(

**Comment by luxyie** [comment]
me too, plz fix it i want to playyy :'bbb

**Comment by Efrox13** [comment]
It happens to me too, it is super annoying to do this thing from the dns, so that in the end I can't enter any server, please fix

**Comment by jimenux253** [comment]
Me too. I have the same problem :(

**Comment by Pugmatt** [comment]
Just a sign-in issue with the Switch version of Minecraft, not unique to BedrockConnect and not much I can do to fix it since it's an issue with the actual game. You can try signing out and closing MC and then reopen and sign in, it may take a few goes. 

I gave the server a reset in case it was being slow, but seems to still be working for most people. If it continues to not work, you can try hosting a local instance. But since it's more an issue with Minecraft Switch version itself, it might not do much: https://www.youtube.com/watch?v=AW5X7-qnvLk
