### ISSUE TITLE
Ps4

### ISSUE THREAD

**Issue by Doc-Lixy** [Pugmatt/BedrockConnect#93]
How to do join serveur Ps4 ?

**Comment by joshuaxlino** [comment]
> How to do join serveur Ps4 ?

It is quite simple:

- Make sure you have the latest java update on your computer before downloading the software 

- Create a notepad and write: java -jar BedrockConnect-1.0-SNAPSHOT.jar nodb=true
(You may need to set the directory so your computer can find it!) 

- Change the .txt to a .bat, this will be your executable and not the .jar file you downloaded

- If done correctly, on ps4 under the friends tab, there should be a world at the very bottom.

If you have questions drop them below

**Comment by big-blanco** [comment]
It seems PS4 got actual servers today. However I have tried to change my DNS server to the one for bedrock connect (and google as secondary) and when doing that I cannot connect my ps4 to the internet. Any insight? Gives me a NW-31253-4 error which seems to mean dns server is unstable or delayed.

**Comment by Hosamawadllah** [comment]
Hosamawadallah

**Comment by JamesTheAwesomeDude** [comment]
I'm also getting `NW-31253-4` on PS4 System Software `8.03` when using Pugmatt's (`104.238.130.180`) primary DNS server. This is not just cosmetic; system functionality is extremely impaired while set.

Two _very strange_ complications:

1. A Nintendo Switch [firmware `11.0.1`] on the same network has **no issues** using Pugmatt's DNS server.
2. Changing the PS4's primary DNS to jdextraze's (`173.82.100.84`) **fixed it** 🎉

(@Pugmatt I'm more than happy to provide any diagnostic information you'd want or find helpful over the next few days; but I'm staying with family at the moment and won't have access to a PS4 in ~1wk; so if there's any info that you'd find helpful, ask it sooner rather than later so I'll have the best chance of being able to provide an answer.)

**Comment by angrynerd** [comment]
Ok so im having an issue with one of my server users. He is connected to the 2nd dns server in the list. The problem is whenever he connects to the list server he gets to the connect to server prompt enters my domain and then ot says disconnected from server. I use geyser fabric but i have other bedrock users who can connect just fine.

**Comment by Pugmatt** [comment]
> Ok so im having an issue with one of my server users. He is connected to the 2nd dns server in the list. The problem is whenever he connects to the list server he gets to the connect to server prompt enters my domain and then ot says disconnected from server. I use geyser fabric but i have other bedrock users who can connect just fine.

Does the error occur after clicking "Submit" on the "Connect to server" prompt? Any errors that occur after that point would typically be on the end of the server they are trying to connect to, not BedrockConnect, as the connection is handed over to the server being connected to at that point.

**Comment by angrynerd** [comment]
Yes my apologies. It seems that it was on there end.
